---
- name: configure yum repos
  include: repos.yml

- name: install selinux management dependency
  yum: name=libsemanage-python state=present
  when: ansible_selinux.status == 'enabled'

- name: install firewalld
  yum: name=firewalld state=present
  when: ansible_distribution_major_version|int > 6
  tags:
    - firewall
    - packages

- name: ensure firewalld is started
  service: name=firewalld state=started enabled=yes
  when: ansible_distribution_major_version|int > 6
  tags:
    - firewall

- name: install development tools
  yum: name="@Development Tools" state=present
  when: common_development_tools
  tags:
    - packages

- name: install extra packages
  yum: name={{ item }} state=present
  with_items: common_extra_packages
  when: common_extra_packages|length > 0
