---
- name: configure yum repos
  include: repos.yml

- name: install selinux fact dependency
  yum: name=libselinux-python state=present
  tags:
    - selinux
    - packages

- name: install selinux management dependency
  yum: name=libsemanage-python state=present
  tags:
    - selinux
    - packages

- name: ensure python crypto is installed
  yum:
    name: python2-cryptography
    state: present
  when: ansible_distribution_major_version|int > 6
  tags:
    - hitch
    - packages

- name: install firewalld
  yum: name=firewalld state=present
  when: ansible_distribution_major_version|int > 6
  tags:
    - firewall
    - packages

- name: ensure firewalld is started
  service: name=firewalld state=started enabled=yes
  when: ansible_distribution_major_version|int > 6
  tags:
    - firewall

- name: install extra packages
  yum: name={{ common_extra_packages }} state=present
  when: common_extra_packages|length > 0
  tags:
    - packages

- name: install development tools
  yum: name="@Development Tools" state=present
  when: common_development_tools|bool
  tags:
    - packages
