---
- name: install epel-release
  yum: name=epel-release state=present
  when: common_install_epel
  tags:
    - repos
    - packages

- name: install remi key
  rpm_key: key=https://rpms.remirepo.net/RPM-GPG-KEY-remi
  when: common_install_remi == true and ansible_distribution_major_version|int > 5
  tags:
    - repos
    - packages

- name: install remi release
  yum: name="https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm" state=present
  when: common_install_remi == true and ansible_distribution_major_version|int > 5
  tags:
    - repos
    - packages
