---
- name: install epel key
  rpm_key: key=http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} state=present
  when: common_install_epel == true or common_install_ius == true
  tags:
    - repos
    - packages

- name: install epel-release
  yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm" state=present
  when: common_install_epel == true or common_install_ius == true
  tags:
    - repos
    - packages

- name: install remi key
  rpm_key: key=https://rpms.remirepo.net/RPM-GPG-KEY-remi
  when: common_install_remi == true and ansible_distribution_major_version|int > 5
  tags:
    - repos
    - packages

- name: install remi release
  yum: name="https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm" state=present
  when: common_install_remi == true and ansible_distribution_major_version|int > 5
  tags:
    - repos
    - packages

- name: install packagecloud key
  rpm_key: key=https://packagecloud.io/gpg.key state=present
  when: common_install_correcthorse == true
  tags:
    - repos
    - packages

- name: install correcthorse
  template: src=correcthorse_batterystaple.repo.j2 dest=/etc/yum.repos.d/correcthorse_batterystaple.repo owner=root group=root mode=0644
  when: common_install_correcthorse == true
  register: correcthorse_repo
  tags:
    - repos
    - packages

- name: accept packagecloud key and update cache
  command: yum -q makecache -y
  when: correcthorse_repo is changed
  tags:
    - repos
    - packages