---
- name: Enable CentOS8 PowerTools repo
  lineinfile: 
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    create: false
    regexp: enabled=
    line: enabled=1
  when: ansible_distribution_major_version == "8" and (common_install_epel or common_install_powertools)
  tags:
    - repos
    - packages

- name: install epel-release
  yum:
    name: epel-release
    state: present
  when: common_install_epel
  tags:
    - repos
    - packages

- block:
    - name: install correcthorse key
      rpm_key:
        key: https://download.correct.horse/correcthorse/RPM-GPG-KEY-CORRECTHORSE
        state: present

    - name: install correcthorse repo
      template:
        src: correcthorse.repo.j2
        dest: /etc/yum.repos.d/correcthorse.repo
        owner: root
        group: root
        mode: 0644

  when: common_install_correcthorse
  tags:
    - repos
    - packages
