---
- name: install epel key
  rpm_key: key=http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} state=present
  tags:
    - repos
    - packages

- name: install epel-release
  yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm" state=present
  tags:
    - repos
    - packages

- name: install ius key
  rpm_key: key=http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY state=present
  tags:
    - repos
    - packages

- name: install ius release for centos
  yum: name="https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm" state=present
  when: ansible_distribution == 'CentOS'
  tags:
    - repos
    - packages

- name: install ius release for rhel
  yum: name="https://rhel{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm" state=present
  when: ansible_distribution != 'CentOS'
  tags:
    - repos
    - packages

- name: install packagecloud key
  rpm_key: key=https://packagecloud.io/gpg.key state=present
  when: common_install_correcthorse == true
  tags:
    - repos
    - packages

- name: install correcthorse
  template: src=correcthorse_batterystaple.repo.j2 dest=/etc/yum.repos.d/correcthorse_batterystaple.repo owner=root group=root mode=0644
  when: common_install_correcthorse == true
  tags:
    - repos
    - packages
