---
- name: install epel key
  rpm_key: key=http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} state=present
  tags:
    - repos
    - packages

- name: template epel config
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=0644
  tags:
    - repos
    - packages

- name: install epel-release
  yum: name=epel-release state=present
  tags:
    - repos
    - packages

- name: install ius key
  rpm_key: key=http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY state=present
  tags:
    - repos
    - packages

- name: template ius config
  template: src=ius.repo.j2 dest=/etc/yum.repos.d/ius.repo owner=root group=root mode=0644
  tags:
    - repos
    - packages

- name: install ius release
  yum: name=ius-release state=present
  tags:
    - repos
    - packages
