---
- name: install epel key
  rpm_key: key=http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} state=present
  when: common_install_epel == true or common_install_ius == true
  tags:
    - repos
    - packages

- name: install epel-release
  yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm" state=present
  when: common_install_epel == true or common_install_ius == true
  tags:
    - repos
    - packages

- name: install ius key
  rpm_key: key=http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY state=present
  when: common_install_ius == true
  tags:
    - repos
    - packages

- name: install ius release for centos
  yum: name="https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm" state=present
  when: common_install_ius == true and ansible_distribution == 'CentOS'
  tags:
    - repos
    - packages

- name: install ius release for rhel
  yum: name="https://rhel{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm" state=present
  when: common_install_ius == true and ansible_distribution != 'CentOS'
  tags:
    - repos
    - packages

- name: install remi key
  rpm_key: key=https://rpms.remirepo.net/RPM-GPG-KEY-remi
  when: common_install_remi == true and ansible_distribution_major_version|int > 5
  tags:
    - repos
    - packages

- name: install remi release
  yum: name="https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm" state=present
  when: common_install_remi == true and ansible_distribution_major_version|int > 5
  tags:
    - repos
    - packages

- name: install webtatic key
  rpm_key: key=https://mirror.webtatic.com/yum/RPM-GPG-KEY-webtatic-el7
  when: common_install_webtatic == true and ansible_distribution_major_version == "7"
  tags:
    - repos
    - packages

- name: install webtatic key for 5/6
  rpm_key: key=https://mirror.webtatic.com/yum/RPM-GPG-KEY-webtatic-andy
  when: common_install_webtatic == true and ansible_distribution_major_version|int < 7
  tags:
    - repos
    - packages

- name: install webtatic-release
  yum: name="https://mirror.webtatic.com/yum/el7/webtatic-release.rpm" state=present
  when: common_install_webtatic == true and ansible_distribution_major_version == "7"
  tags:
    - repos
    - packages

- name: install webtatic-release for 5/6
  yum: name="https://mirror.webtatic.com/yum/el{{ ansible_distribution_major_version }}/latest.rpm" state=present
  when: common_install_webtatic == true and ansible_distribution_major_version|int < 7
  tags:
    - repos
    - packages

- name: install packagecloud key
  rpm_key: key=https://packagecloud.io/gpg.key state=present
  when: common_install_correcthorse == true
  tags:
    - repos
    - packages

- name: install correcthorse
  template: src=correcthorse_batterystaple.repo.j2 dest=/etc/yum.repos.d/correcthorse_batterystaple.repo owner=root group=root mode=0644
  when: common_install_correcthorse == true
  register: correcthorse_repo
  tags:
    - repos
    - packages

- name: accept packagecloud key and update cache
  command: yum -q makecache -y
  when: correcthorse_repo|changed
  tags:
    - repos
    - packages