---
- name: reload firewall
  command: firewall-cmd --reload
  when: ansible_distribution_major_version == "7"

- name: reload systemd
  command: systemctl daemon-reload
  when: ansible_distribution_major_version == "7"